service:
  name: kui-demo-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getLatest:
    handler: handler.getLatest
    events:
      - http:
          method: get
          path: getLatest
          cors: true

  getSession:
    handler: handler.getSession
    events:
      - http:
          method: get
          path: getSession/{id}
          request:
             parameters:
               paths:
                 id: true
          cors: true
